name: coldcopy-api
region: nyc
services:
  - name: coldcopy
    environment_slug: python
    github:
      repo: codevanmoose/coldcopy
      branch: main
      deploy_on_push: true
    source_dir: /
    build_command: "cd apps/api && pip install -r requirements-do.txt"
    run_command: "cd apps/api && uvicorn main_simple:app --host 0.0.0.0 --port 8000"
    http_port: 8000
    instance_count: 1
    instance_size_slug: basic-xxs