spec:
  name: coldcopy-api
  region: nyc
  services:
  - dockerfile_path: apps/api/Dockerfile
    github:
      branch: main
      deploy_on_push: true
      repo: codevanmoose/coldcopy
    http_port: 8000
    instance_count: 1
    instance_size_slug: basic-xxs
    name: coldcopy
    source_dir: /