spec:
  name: coldcopy-api
  region: nyc
  services:
  - build_command: cd apps/api && pip install -r requirements-do.txt
    environment_slug: python
    github:
      branch: main
      deploy_on_push: true
      repo: codevanmoose/coldcopy
    http_port: 8000
    instance_count: 1
    instance_size_slug: basic-xxs
    name: coldcopy
    run_command: cd apps/api && uvicorn main_simple:app --host 0.0.0.0 --port 8000
    source_dir: /