# Digital Ocean App Platform Specification
# Deploy with: doctl apps create --spec app.yaml

name: coldcopy-app
region: nyc

# Environment variables (add actual values in DO dashboard)
envs:
  - key: NODE_ENV
    value: production
    scope: RUN_AND_BUILD_TIME
  - key: NEXT_PUBLIC_SUPABASE_URL
    value: ${NEXT_PUBLIC_SUPABASE_URL}
    scope: BUILD_TIME
  - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
    value: ${NEXT_PUBLIC_SUPABASE_ANON_KEY}
    scope: BUILD_TIME
  - key: NEXT_PUBLIC_APP_URL
    value: https://coldcopy.cc
    scope: BUILD_TIME
  - key: NEXT_PUBLIC_API_URL
    value: https://api.coldcopy.cc
    scope: BUILD_TIME

services:
  # Main Next.js application
  - name: web
    dockerfile_path: infrastructure/docker/Dockerfile
    source_dir: /
    github:
      branch: main
      deploy_on_push: true
      repo: codevanmoose/coldcopy
    
    # Environment variables
    envs:
      - key: DATABASE_URL
        value: ${DATABASE_URL}
        type: SECRET
        scope: RUN_TIME
      - key: SUPABASE_SERVICE_ROLE_KEY
        value: ${SUPABASE_SERVICE_ROLE_KEY}
        type: SECRET
        scope: RUN_TIME
      - key: NEXTAUTH_SECRET
        value: ${NEXTAUTH_SECRET}
        type: SECRET
        scope: RUN_TIME
      - key: JWT_SECRET
        value: ${JWT_SECRET}
        type: SECRET
        scope: RUN_TIME
      - key: ENCRYPTION_KEY
        value: ${ENCRYPTION_KEY}
        type: SECRET
        scope: RUN_TIME
      - key: AWS_ACCESS_KEY_ID
        value: ${AWS_ACCESS_KEY_ID}
        type: SECRET
        scope: RUN_TIME
      - key: AWS_SECRET_ACCESS_KEY
        value: ${AWS_SECRET_ACCESS_KEY}
        type: SECRET
        scope: RUN_TIME
      - key: OPENAI_API_KEY
        value: ${OPENAI_API_KEY}
        type: SECRET
        scope: RUN_TIME
      - key: ANTHROPIC_API_KEY
        value: ${ANTHROPIC_API_KEY}
        type: SECRET
        scope: RUN_TIME
      - key: STRIPE_SECRET_KEY
        value: ${STRIPE_SECRET_KEY}
        type: SECRET
        scope: RUN_TIME
      - key: REDIS_URL
        value: ${redis.REDIS_URL}
        scope: RUN_TIME
      - key: CRON_SECRET
        value: ${CRON_SECRET}
        type: SECRET
        scope: RUN_TIME
    
    # HTTP settings
    http_port: 3000
    
    # Instance configuration
    instance_count: 2
    instance_size_slug: professional-xs
    
    # Health check
    health_check:
      http_path: /api/health
      initial_delay_seconds: 40
      period_seconds: 30
      timeout_seconds: 3
      success_threshold: 1
      failure_threshold: 3
    
    # Routes
    routes:
      - path: /
    
    # Auto-scaling
    alerts:
      - rule: CPU_UTILIZATION
        value: 80
        operator: GREATER_THAN
        window: FIVE_MINUTES
      - rule: MEM_UTILIZATION
        value: 90
        operator: GREATER_THAN
        window: FIVE_MINUTES

# Databases
databases:
  - name: redis
    engine: REDIS
    version: "7"
    size: db-s-1vcpu-1gb
    num_nodes: 1

# Jobs (for background tasks)
jobs:
  # Database maintenance
  - name: db-maintenance
    kind: PRE_DEPLOY
    github:
      branch: main
      repo: codevanmoose/coldcopy
    source_dir: /
    run_command: |
      cd infrastructure/database
      psql $DATABASE_URL < optimize_database.sql
    envs:
      - key: DATABASE_URL
        value: ${DATABASE_URL}
        type: SECRET
        scope: RUN_TIME

# Domains
domains:
  - domain: api.coldcopy.cc
    type: PRIMARY
    zone: coldcopy.cc
  - domain: track.coldcopy.cc
    type: ALIAS
    zone: coldcopy.cc