#cloud-config
package_update: true
package_upgrade: true

packages:
  - docker.io
  - docker-compose
  - ufw
  - fail2ban
  - htop
  - vim
  - git
  - certbot
  - python3-certbot-nginx

users:
  - name: coldcopy
    groups: sudo, docker
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh_authorized_keys:
      - ssh-rsa YOUR_PUBLIC_SSH_KEY

write_files:
  - path: /etc/docker/daemon.json
    content: |
      {
        "log-driver": "json-file",
        "log-opts": {
          "max-size": "10m",
          "max-file": "3"
        },
        "metrics-addr": "0.0.0.0:9323",
        "experimental": true
      }

  - path: /etc/systemd/system/coldcopy.service
    content: |
      [Unit]
      Description=ColdCopy API Service
      Requires=docker.service
      After=docker.service

      [Service]
      Type=oneshot
      RemainAfterExit=yes
      User=coldcopy
      WorkingDirectory=/home/coldcopy/app
      ExecStart=/usr/bin/docker-compose up -d
      ExecStop=/usr/bin/docker-compose down
      TimeoutStartSec=0

      [Install]
      WantedBy=multi-user.target

runcmd:
  # Configure firewall
  - ufw default deny incoming
  - ufw default allow outgoing
  - ufw allow ssh
  - ufw allow http
  - ufw allow https
  - ufw allow 9090/tcp  # Prometheus
  - ufw allow 3000/tcp  # Grafana
  - ufw --force enable

  # Configure fail2ban
  - systemctl enable fail2ban
  - systemctl start fail2ban

  # Setup Docker
  - systemctl enable docker
  - systemctl start docker
  - usermod -aG docker coldcopy

  # Create app directory
  - mkdir -p /home/coldcopy/app
  - chown -R coldcopy:coldcopy /home/coldcopy/app

  # Setup swap
  - fallocate -l 2G /swapfile
  - chmod 600 /swapfile
  - mkswap /swapfile
  - swapon /swapfile
  - echo '/swapfile none swap sw 0 0' >> /etc/fstab

  # System optimizations
  - echo 'vm.swappiness=10' >> /etc/sysctl.conf
  - echo 'net.core.somaxconn=65535' >> /etc/sysctl.conf
  - echo 'net.ipv4.tcp_max_syn_backlog=65535' >> /etc/sysctl.conf
  - sysctl -p

  # Setup automatic security updates
  - apt-get install -y unattended-upgrades
  - dpkg-reconfigure -plow unattended-upgrades

  # Clone repository (optional, or use CI/CD)
  # - git clone https://github.com/coldcopy/coldcopy.git /home/coldcopy/app
  # - chown -R coldcopy:coldcopy /home/coldcopy/app

  # Enable ColdCopy service
  - systemctl daemon-reload
  - systemctl enable coldcopy.service

  # Setup log rotation
  - |
    cat > /etc/logrotate.d/coldcopy << EOF
    /home/coldcopy/app/logs/*.log {
        daily
        rotate 14
        compress
        delaycompress
        missingok
        notifempty
        create 0640 coldcopy coldcopy
        sharedscripts
        postrotate
            docker-compose -f /home/coldcopy/app/docker-compose.yml kill -s USR1 nginx
        endscript
    }
    EOF

  # Reboot to apply all changes
  - reboot