name: coldcopy-api
region: nyc
envs:
- key: PYTHON_VERSION
  scope: BUILD_TIME
  value: "3.11.7"
services:
- build_command: pip install -r requirements-do.txt
  environment_slug: python
  github:
    branch: main
    deploy_on_push: true
    repo: jaspermeet/coldcopy
  http_port: 8000
  instance_count: 1
  instance_size_slug: basic-xxs
  name: api
  run_command: uvicorn main_simple:app --host 0.0.0.0 --port 8000
  source_dir: /apps/api